In [4]:
import pandas as pd

df = pd.read_csv('ab_data.csv')
df.head()

   user_id                   timestamp      group landing_page  converted
0   851104  2017-01-21 22:11:48.556739    control     old_page          0
1   804228  2017-01-12 08:01:45.159739    control     old_page          0
2   661590  2017-01-11 16:55:06.154213  treatment     new_page          0
3   853541  2017-01-08 18:28:03.143765  treatment     new_page          0
4   864975  2017-01-21 01:52:26.210827    control     old_page          1

In [16]:
df.groupby('group')['converted'].mean()

group
control      0.120399
treatment    0.118920
Name: converted, dtype: float64

In [17]:
from scipy import stats

A = df[df['group']=='control']['converted']
B = df[df['group']=='treatment']['converted']

stats.ttest_ind(A, B)

TtestResult(statistic=np.float64(1.2369207675839395), pvalue=np.float64(0.21611748562490837), df=np.float64(294476.0))